name: "unit tests"
on:
  push:
jobs:
  go-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run Tests
        id: tests
        run: |
          go test -race ./... 
